# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tk7ShBYOL6YtaIB3W8L-kfqQHuBf3Ew1
"""

from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives import hashes, hmac
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
import os

# Greek text example
greek_text = "Γειά σου Κόσμε"  # "Hello World" in Greek
encoded_text = greek_text.encode('iso-8859-7')

# Key and IV generation
key = os.urandom(16)  # 128-bit key
iv = os.urandom(16)   # Initialization Vector

# Encryption (ESP-like functionality)
cipher = Cipher(algorithms.AES(key), modes.CFB(iv))
encryptor = cipher.encryptor()
ciphertext = encryptor.update(encoded_text) + encryptor.finalize()

# Integrity Check (AH-like functionality)
h = hmac.HMAC(key, hashes.SHA256())
h.update(ciphertext)
auth_tag = h.finalize()

# Output
print("Original Greek Text:", greek_text)
print("Encoded Text:", encoded_text)
print("Ciphertext:", ciphertext)
print("Authentication Tag:", auth_tag)

##################################################################
Original Greek Text: Γειά σου Κόσμε
Encoded Text: b'\xc3\xe5\xe9\xdc \xf3\xef\xf5 \xca\xfc\xf3\xec\xe5'
Ciphertext: b'\xeb\\\x00C*\xb5\x88T@3\xac\xfe\x7f\x06'
Authentication Tag: b'\t\x9c\xf7C\x08\xfe\xbd.\xfd\xf2\xb4\x19~\xd7/\x06\xac\x8b\x1a9\xb0\x8f\x1aa&\xe2\x199\xdd\xd0\x13I'

