# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tk7ShBYOL6YtaIB3W8L-kfqQHuBf3Ew1
"""

import socket
import ssl

# Define server details
hostname = 'example.com'
port = 443

# Create a socket and wrap it with SSL
context = ssl.create_default_context()
with socket.create_connection((hostname, port)) as sock:
    with context.wrap_socket(sock, server_hostname=hostname) as ssock:
        print(f"SSL established. Peer: {ssock.getpeercert()}")

import requests

url = 'https://example.com'

# Make a secure GET request
response = requests.get(url, verify=True)  # 'verify=True' ensures SSL verification
print(response.status_code)
print(response.text)

