# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tk7ShBYOL6YtaIB3W8L-kfqQHuBf3Ew1
"""

!pip install kerberos

import kerberos

def kerberos_authenticate(service_name):
    try:
        # Initialize the server-side context
        context = kerberos.authGSSServerInit(service_name)
        kerberos.authGSSServerStep(context, "")

        # Retrieve the authenticated username
        username = kerberos.authGSSServerUserName(context)
        print(f"Authenticated user: {username}")

        # Clean up the context
        kerberos.authGSSServerClean(context)
    except kerberos.GSSError as e:
        print(f"Kerberos authentication failed: {e}")

# Example usage
kerberos_authenticate("HTTP@your-server-name")

import random

def generate_otp(length=6):
    otp = ''.join([str(random.randint(0, 9)) for _ in range(length)])
    return otp

# Example usage
otp = generate_otp()
print(f"Your OTP is: {otp}")

