# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tk7ShBYOL6YtaIB3W8L-kfqQHuBf3Ew1
"""

from cryptography import x509
from cryptography.hazmat.backends import default_backend

# Load the certificate from a file
with open("certificate.pem", "rb") as cert_file:
    cert_data = cert_file.read()

# Parse the certificate
certificate = x509.load_pem_x509_certificate(cert_data, default_backend())

# Print certificate details
print("Subject:", certificate.subject)
print("Issuer:", certificate.issuer)
print("Serial Number:", certificate.serial_number)
print("Validity Period:", certificate.not_valid_before, "to", certificate.not_valid_after)

#####################################################################################################
Subject: <Name(C=GR,ST=Attica,L=Athens,O=My Greek Organization,CN=example.com)>
Issuer: <Name(C=GR,ST=Attica,L=Athens,O=My Greek Organization,CN=example.com)>
Serial Number: 379220844012012984636481580053958215356879130357
Validity Period: 2025-08-22 18:43:22 to 2026-08-22 18:43:22
/tmp/ipython-input-4159274874.py:15: CryptographyDeprecationWarning: Properties that return a naïve datetime object have been deprecated. Please switch to not_valid_before_utc.
  print("Validity Period:", certificate.not_valid_before, "to", certificate.not_valid_after)
/tmp/ipython-input-4159274874.py:15: CryptographyDeprecationWarning: Properties that return a naïve datetime object have been deprecated. Please switch to not_valid_after_utc.
  print("Validity Period:", certificate.not_valid_before, "to", certificate.not_valid_after)


