# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tk7ShBYOL6YtaIB3W8L-kfqQHuBf3Ew1
"""

import re

# RFC 5322-compliant email regex
RFC5322_REGEX = r"^(?!\.)[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+(?<!\.)@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$"

def is_valid_email(email):
    """Validate email address against RFC 5322."""
    return re.match(RFC5322_REGEX, email) is not None

# Test cases
emails = [
    "example@example.com",
    "user.name+tag+sorting@example.com",
    "user@sub.example.com",
    "invalid-email@.com",
    "another.invalid@domain..com"
]

for email in emails:
    print(f"{email}: {'Valid' if is_valid_email(email) else 'Invalid'}")

########################################################
example@example.com: Valid
user.name+tag+sorting@example.com: Valid
user@sub.example.com: Valid
invalid-email@.com: Invalid
another.invalid@domain..com: Invalid

