# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tk7ShBYOL6YtaIB3W8L-kfqQHuBf3Ew1
"""

from google.colab import files

# Upload files
uploaded = files.upload()  # Choose reference_signature.jpg and user_signature.jpg

import os
print(os.listdir())

import cv2
import numpy as np
from skimage.metrics import structural_similarity as ssim

def compare_signatures(reference_path, user_path):
    # Load the reference and user signature images
    reference_img = cv2.imread(reference_path, 0)
    user_img = cv2.imread(user_path, 0)

    # Check if images were loaded
    if reference_img is None:
        raise FileNotFoundError(f"Reference image not found: {reference_path}")
    if user_img is None:
        raise FileNotFoundError(f"User image not found: {user_path}")

    # Resize images to the same size
    reference_img = cv2.resize(reference_img, (300, 300))
    user_img = cv2.resize(user_img, (300, 300))

    # Compute Structural Similarity Index (SSIM)
    score, _ = ssim(reference_img, user_img, full=True)

    # Threshold for authentication
    threshold = 0.8
    return "Authentication Successful" if score >= threshold else "Authentication Failed"